name: celeri
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - addict=2.4.0=pyhd8ed1ab_2
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.9.0=pyh29332c3_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py312h024a12e_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - astropy-base=7.1.0=py312hb89d667_0
  - astropy-iers-data=0.2025.6.9.0.39.3=pyhd8ed1ab_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.4=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blosc=1.21.6=h7dd00d9_1
  - branca=0.8.1=pyhd8ed1ab_0
  - brotli=1.1.0=h5505292_3
  - brotli-bin=1.1.0=h5505292_3
  - brotli-python=1.1.0=py312hd8f9ff3_3
  - bzip2=1.0.8=h99b78c6_7
  - c-ares=1.34.5=h5505292_0
  - c-compiler=1.10.0=hdf49b6b_0
  - ca-certificates=2025.7.9=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h6a3b0d2_0
  - cctools=1010.6=hb4fb6a3_6
  - cctools_osx-arm64=1010.6=h3b4f5d3_6
  - certifi=2025.7.9=pyhd8ed1ab_0
  - cffi=1.17.1=py312h0fad829_0
  - cftime=1.6.4=py312h755e627_1
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - clang=18.1.8=default_h474c9e2_10
  - clang-18=18.1.8=default_hf90f093_10
  - clang_impl_osx-arm64=18.1.8=h2ae9ea5_25
  - clang_osx-arm64=18.1.8=h07b0088_25
  - clangxx=18.1.8=default_h1ffe849_10
  - clangxx_impl_osx-arm64=18.1.8=h555f467_25
  - clangxx_osx-arm64=18.1.8=h07b0088_25
  - clarabel=0.11.1=py312hfb10456_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorcet=3.1.0=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - compiler-rt=18.1.8=h856b3c1_1
  - compiler-rt_osx-arm64=18.1.8=h832e737_1
  - compilers=1.10.0=hce30654_0
  - contourpy=1.3.2=py312hb23fbb9_0
  - cpython=3.12.11=py312hd8ed1ab_0
  - crc32c=2.7.1=py312hea69d52_1
  - curl=8.14.1=h73640d1_0
  - cutde=23.6.25=py312hb2fcc66_4
  - cvxopt=1.3.2=py312hc9c70d4_4
  - cvxpy=1.5.3=py312h1f38498_0
  - cvxpy-base=1.5.3=py312h8ae5369_0
  - cxx-compiler=1.10.0=hba80287_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dcw-gmt=2.2.0=hce30654_0
  - debugpy=1.8.14=py312hd8f9ff3_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - dill=0.4.0=pyhd8ed1ab_0
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - dsdp=5.8=h9397a75_1203
  - ecos=2.0.14=py312h755e627_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - fftw=3.3.10=nompi_h6637ab6_110
  - fltk=1.3.10=h46aaf7c_0
  - folium=0.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.5=py312h998013c_0
  - fortran-compiler=1.10.0=h5692697_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freeimage=3.18.0=h2e169f6_22
  - freetype=2.13.3=hce30654_1
  - freexl=2.0.0=h3ab3353_2
  - geopandas=1.1.1=pyhd8ed1ab_0
  - geopandas-base=1.1.1=pyha770c72_0
  - geos=3.13.1=hc9a1286_0
  - gfortran=13.4.0=h3ef1dbf_0
  - gfortran_impl_osx-arm64=13.4.0=h64b5c3f_0
  - gfortran_osx-arm64=13.4.0=h3c33bd0_0
  - ghostscript=10.04.0=hf9b8971_0
  - giflib=5.2.2=h93a5062_0
  - glpk=5.0=h6d7a090_0
  - gmp=6.3.0=h7bae524_2
  - gmt=6.5.0=hf581852_10
  - gshhg-gmt=2.3.7=hce30654_1003
  - gsl=2.7=h6e638da_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.14.0=nompi_py312h35183de_100
  - hdf4=4.2.15=h2ee6834_7
  - hdf5=1.14.6=nompi_ha698983_101
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.10=pyhd8ed1ab_1
  - imath=3.1.12=h025cafa_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - ipykernel=6.29.5=pyh57ce528_0
  - ipympl=0.9.7=pyhd8ed1ab_1
  - ipython=9.4.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isl=0.26=imath32_h347afa1_101
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jasper=4.2.5=h743e416_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - json-c=0.18=he4178ee_0
  - json5=0.12.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py312h81bd7bf_1
  - jsonschema=4.24.0=pyhd8ed1ab_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.24.0=hd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhe01879c_2
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.16.0=pyhe01879c_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.4=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - jxrlib=1.1=h93a5062_3
  - kiwisolver=1.4.8=py312hb23fbb9_1
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - ld64=951.9=h4c6efb1_6
  - ld64_osx-arm64=951.9=hb6b49e2_6
  - lerc=4.0.0=hd64df32_1
  - libaec=1.1.4=h51d1e36_0
  - libamd=3.3.3=h5087772_7100102
  - libarchive=3.8.1=gpl_h46e8061_100
  - libblas=3.9.0=32_h10e41b3_openblas
  - libbrotlicommon=1.1.0=h5505292_3
  - libbrotlidec=1.1.0=h5505292_3
  - libbrotlienc=1.1.0=h5505292_3
  - libbtf=2.3.2=h99b4a89_7100102
  - libcamd=3.3.3=h99b4a89_7100102
  - libcblas=3.9.0=32_hb3479ef_openblas
  - libccolamd=3.3.4=h99b4a89_7100102
  - libcholmod=5.3.1=hbba04d7_7100102
  - libclang-cpp18.1=18.1.8=default_hf90f093_10
  - libcolamd=3.3.4=h99b4a89_7100102
  - libcurl=8.14.1=h73640d1_0
  - libcxsparse=4.4.1=h9e79f82_7100102
  - libcxx=20.1.8=ha82da77_0
  - libcxx-devel=18.1.8=h6dc3340_8
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.0=h286801f_0
  - libffi=3.4.6=h1da3d7d_1
  - libfreetype=2.13.3=hce30654_1
  - libfreetype6=2.13.3=h1d14073_1
  - libgdal-core=3.11.2=hc8edae9_0
  - libgdal-jp2openjpeg=3.11.2=h82802c5_0
  - libgfortran=5.0.0=14_2_0_h6c33f7e_103
  - libgfortran-devel_osx-arm64=13.4.0=ha240a38_0
  - libgfortran5=14.2.0=h6c33f7e_103
  - libglib=2.84.2=hbec27ea_0
  - libhwy=1.2.0=h9a9ea7e_0
  - libiconv=1.18=hfe07756_1
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - libjxl=0.11.1=h72d67bc_2
  - libklu=2.3.5=h4370aa4_7100102
  - libkml=1.3.0=he250239_1021
  - liblapack=3.9.0=32_hc9a63f6_openblas
  - libldl=3.3.2=h99b4a89_7100102
  - libllvm18=18.1.8=hc4b4ae8_3
  - liblzma=5.8.1=h39f12f2_2
  - libnetcdf=4.9.2=nompi_h3352478_117
  - libnghttp2=1.64.0=h6d7220d_0
  - libopenblas=0.3.30=openmp_hf332438_0
  - libosqp=0.6.3=h5833ebf_1
  - libparu=1.0.0=h317a14d_7100102
  - libpng=1.6.50=h3783ad8_0
  - libqdldl=0.1.7=hb7217d7_0
  - libraw=0.21.4=h62a31ad_0
  - librbio=4.3.4=h99b4a89_7100102
  - librttopo=1.1.0=h26cc057_18
  - libsodium=1.0.20=h99b78c6_0
  - libspatialite=5.1.0=hea0a7cd_14
  - libspex=3.2.3=h15d103f_7100102
  - libspqr=4.3.4=h775d698_7100102
  - libsqlite=3.50.2=hf8de324_2
  - libssh2=1.11.1=h1590b86_0
  - libsuitesparseconfig=7.10.1=h4a8fc20_7100102
  - libtiff=4.7.0=h2f21f7c_5
  - libumfpack=6.3.5=h7c2c975_7100102
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.8=h52572c6_0
  - libxslt=1.1.39=h223e5b9_0
  - libzip=1.11.2=h1336266_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=20.1.7=hdb05f8b_0
  - llvm-tools=18.1.8=hc4b4ae8_3
  - llvm-tools-18=18.1.8=hc4b4ae8_3
  - loguru=0.7.3=pyh707e725_0
  - lxml=6.0.0=py312hc2c121e_0
  - lz4-c=1.10.0=h286801f_1
  - lzo=2.10=h93a5062_1001
  - mako=1.3.10=pyhd8ed1ab_0
  - mapclassify=2.10.0=pyhd8ed1ab_1
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py312h998013c_1
  - matplotlib=3.10.3=py312h1f38498_0
  - matplotlib-base=3.10.3=py312hdbc7e53_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - meshio=5.3.5=pyhd8ed1ab_0
  - metis=5.1.0=h15f6cfe_1007
  - minizip=4.0.10=hff1a8ea_0
  - mistune=3.1.3=pyh29332c3_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - msgpack-python=1.1.1=py312hb23fbb9_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - muparser=2.3.5=h11e0b38_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf4=1.7.2=nompi_py312h3abf214_102
  - networkx=3.5=pyhe01879c_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numcodecs=0.16.1=py312hcb1e3ce_0
  - numpy=1.26.4=py312h8442bc7_0
  - occt=7.8.1=novtk_hbec2736_103
  - openexr=3.3.4=h37c74dd_0
  - openjpeg=2.5.3=h8a3d83b_0
  - openssl=3.5.1=h81ee809_0
  - osqp=0.6.7.post3=py312h72a45a2_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.1=py312h98f7732_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre=8.45=hbdafb3b_0
  - pcre2=10.45=ha881caa_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py312h50aef2c_0
  - pip=25.1.1=pyh8b19718_0
  - pixman=0.46.2=h2f9eb0b_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.8=pyhe01879c_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - polars=1.31.0=default_h56a14c1_0
  - polars-default=1.31.0=py39h6da47c3_0
  - proj=9.6.2=h1318a7e_0
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py312hea69d52_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-global=2.13.6=pyh217bc35_3
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.7=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py312hd3c0895_0
  - pyerfa=2.0.1.5=py312he0011b7_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pygmt=0.16.0=pyhd8ed1ab_0
  - pyobjc-core=11.1=py312h4c66426_0
  - pyobjc-framework-cocoa=11.1=py312hb9d441b_0
  - pyogrio=0.11.0=py312hf1cabc8_1
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyproj=3.7.1=py312h237c406_1
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=8.4.1=pyhd8ed1ab_0
  - python=3.12.11=hc22306f_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-gil=3.12.11=hd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=7_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h998013c_2
  - pyzmq=27.0.0=py312hf4875e0_0
  - qdldl-python=0.1.7.post5=np20py312h7ca56ae_1
  - qhull=2020.2=h420ef59_5
  - rapidjson=1.1.0.post20240409=ha1acc90_2
  - readline=8.2=h1d1bf99_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.4=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=14.0.0=pyh29332c3_0
  - rpds-py=0.26.0=py312hd3c0895_0
  - scikit-learn=1.7.0=py312h39203ce_1
  - scipy=1.16.0=py312hcedbd36_0
  - scs=3.2.7.post2=default_py312h2836932_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.1.1=py312hf733f26_0
  - sigtool=0.1.3=h44b9a77_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h98b9ce2_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.7=pyhd8ed1ab_0
  - spherical-geometry=1.3.2=py312hcb1e3ce_4
  - sqlite=3.50.2=h6e44f1d_2
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py312hcde60ef_0
  - suitesparse=7.10.1=h3071b36_7100102
  - tapi=1300.6.5=h03f4b80_0
  - terminado=0.18.1=pyh31c8845_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h892fb3f_2
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.5.1=py312hea69d52_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250708=pyhd8ed1ab_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py312hea69d52_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - uriparser=0.9.8=h00cdb27_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - wrapt=1.17.2=py312hea69d52_0
  - xarray=2025.7.1=pyhd8ed1ab_0
  - xerces-c=3.2.5=h92fc2f4_2
  - xorg-libice=1.1.2=h5505292_0
  - xorg-libsm=1.2.6=h5505292_0
  - xorg-libx11=1.8.12=h6a5fb8c_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xorg-libxext=1.3.6=hd74edd7_0
  - xorg-libxfixes=6.0.1=hd74edd7_0
  - xorg-libxrender=0.9.12=h5505292_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - yaml=0.2.5=h3422bc3_2
  - zarr=3.0.10=pyhd8ed1ab_0
  - zeromq=4.3.5=hc1bb282_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zstandard=0.23.0=py312hea69d52_2
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - celeri==0.0.2.post1.dev300+g6719c25
      - gmsh==4.14.0
      - ismember==1.1.0
      - okada-wrapper==24.6.15
prefix: /opt/anaconda3/envs/celeri
